### PR TITLE
Enhanced

### PR DESCRIPTION
**Pull request by DanielRivasMD**
Implemented additional vim movements:
h,l, J, K, H, L as well as zooming options.

### CODE REVIEW

**Comment by xrisk** [comment]
@DanielRivasMD hi why'd you close the PR? it seems very good I will merge it soon :)

**Comment by DanielRivasMD** [comment]
I have an additional commit that wanted to include, but I will reopen this PR first

**Comment by xrisk** [comment]
Sure, please add your name to the readme when you're done! Thanks for the great work

**Comment by DanielRivasMD** [comment]
I updated the README to include documentation. Let me know what you think. Cheers

**Comment by xrisk** [comment]
Thank you! I will probably submit this to the official Karabiner repo soon. Hope that's okay with you.

**Pull request merged**
